### PR TITLE
Update to support react 0.14.0

### PR DESCRIPTION
**Pull request by framerate**

### CODE REVIEW

**Comment by qimingweng** [comment]
Actually, @framerate, we don't need to rely on react-dom because react will automatically use the ref when it's an html element.

**Comment by qimingweng** [comment]
But thanks for remindig me to do this! I'll get to it as soon as I can.

**Comment by qimingweng** [comment]
I've made further changes on #2 so I won't merge this

**Comment by qimingweng** [comment]
@framerate Also merged and semver-major change to 2.0.0

**Comment by framerate** [comment]
Awesome! Great work! I missed that in the docs, so you just taught me something! Thanks :)

**Pull request closed without merging**
